In [1]:
import numpy as np

In [3]:
A=np.array([[5,346,346,64],
           [2345,256,26,26],
           [235,2365,26,62,]])
print(A)

[[   5  346  346   64]
 [2345  256   26   26]
 [ 235 2365   26   62]]


In [19]:
cal=A.sum(axis=0)#vertical sum

In [20]:
cal

array([2585, 2967,  398,  152])

In [21]:
percentage=A*100/cal.reshape(1,4)

In [22]:
percentage

array([[ 0.1934236 , 11.66161105, 86.93467337, 42.10526316],
       [90.71566731,  8.62824402,  6.53266332, 17.10526316],
       [ 9.09090909, 79.71014493,  6.53266332, 40.78947368]])