In [1]:
import numpy as np

In [3]:
a=np.random.randn(5)
#rank 1 matrix

print(a.shape)

(5,)


In [4]:
print(a)

[-0.51498799  1.07959945 -0.34496698  0.47511888 -0.71100092]


In [5]:
print(a.T)

[-0.51498799  1.07959945 -0.34496698  0.47511888 -0.71100092]


In [6]:
print(np.dot(a,a.T))

2.281010081130419


In [7]:
a=np.random.rand(5,1)

In [9]:
#column vector
print(a.shape)
print(a)


(5, 1)
[[0.57974343]
 [0.84445801]
 [0.57371455]
 [0.82441624]
 [0.59708838]]


In [11]:
a=np.random.rand(1,5)
#row matrix
print(a.shape)
print(a)

(1, 5)
[[0.73223935 0.96209992 0.99212006 0.32264492 0.58258385]]


In [13]:
print(a.shape)

(1, 5)


In [14]:
#verification of dimension

assert(a.shape==(1,5))