In [2]:
import numpy as np

In [8]:
a=np.random.randn(4,3)
b=np.random.randn(3,2)
print(a)
print(b)
print(a*b)

[[ 0.67914615 -0.22794286  0.70954413]
 [-0.07859961  1.72148045 -0.46248703]
 [-0.09355144 -1.0584464   1.3124366 ]
 [ 0.08194776 -0.59274748 -1.00694779]]
[[ 0.52422153 -0.97819663]
 [ 2.26585338  0.21218534]
 [-0.59878476 -0.58898773]]


ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [5]:
-1.08015227* 0.99865662

-1.0787012150435273