In [3]:
# 2 dimension data: Data from csv file,excel ,database tables
import numpy as np

In [4]:
matrix=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [5]:
print(matrix.shape) #dimension details(no of row,no of columns)

(3, 3)


In [6]:
print(matrix.size) # number of elements


9


In [7]:
matrix[0,0] # Row 1 & column1

1

In [8]:
matrix[2,2]

9

In [10]:
matrix[0,:] # first row all columns

array([1, 2, 3])

In [12]:
matrix[:,0] # first column all row

array([1, 4, 7])

In [13]:
matrix[1,:] # second raw all columns

array([4, 5, 6])

In [15]:
matrix[:,1] # second columns all row

array([2, 5, 8])

In [19]:
# change the dimension of data
matrix2=np.arange(100).reshape(10,10)
matrix2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [20]:
matrix3=np.arange(100).reshape(10,10)
matrix3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [22]:

matrix4=matrix3+matrix2
matrix4

array([[  0,   2,   4,   6,   8,  10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48,  50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108, 110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128, 130, 132, 134, 136, 138],
       [140, 142, 144, 146, 148, 150, 152, 154, 156, 158],
       [160, 162, 164, 166, 168, 170, 172, 174, 176, 178],
       [180, 182, 184, 186, 188, 190, 192, 194, 196, 198]])

In [24]:
matrix5=np.dot(matrix2,matrix3) # matrix multiplication
matrix5.shape

(10, 10)

In [25]:
matrix2*matrix3 # normal multiplication

array([[   0,    1,    4,    9,   16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225,  256,  289,  324,  361],
       [ 400,  441,  484,  529,  576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521],
       [1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401],
       [2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481],
       [3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761],
       [4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241],
       [6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921],
       [8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]])

In [26]:
matrix6=np.arange(10).reshape(5,2)
matrix6

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
matrix6.sum(axis=0) # do summation takin one column at a time ,axis=0 

array([20, 25])

In [29]:
matrix6.sum(axis=1) # do summation takin one row at a time ,axis=1 

array([ 1,  5,  9, 13, 17])

In [31]:
matrix6.sum() # sum of all elements in the matrix


45

In [32]:
matrix6.mean(axis=0) # column wise average

array([4., 5.])

In [34]:
np.eye(5,5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
matrix6.reshape(matrix6.size,1) #(1,10) # 2 D data

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [36]:
matrix6.flatten() # single list and 1D data 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
array6=matrix6.ravel() # similar to flatten a data 1 D data
array6.shape

(10,)

In [46]:
### 3 D  data

In [45]:
x3=np.array([[[1,2],[3,4]],
             [[5,6],[7,8]],
          [[9,10],[11,11]]
            ])
x3.shape
# 3 rows 2 columns and two such tables

(3, 2, 2)

In [47]:
x3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 11]]])

In [48]:
y3=np.arange(8).reshape(2,2,2)
y3.shape

(2, 2, 2)

In [49]:
y3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [53]:
y3[:,:,0]
#all rows,all columns ,index 0 or first layer or first table alone or z axis

array([[0, 2],
       [4, 6]])

In [54]:
#first row,all columns,from all tables

In [55]:
y3[0,:,:]

array([[0, 1],
       [2, 3]])

In [56]:
y3[1,0,1]

5

In [58]:
yy3=np.arange(27).reshape(3,3,3)
yy3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [59]:
yy3[:,[1,2],2]

array([[ 5,  8],
       [14, 17],
       [23, 26]])

In [65]:
yy3[0:2,0:2,0]

array([[ 0,  3],
       [ 9, 12]])